Remove -e from check-html
It doesn’t work on Travis

diff --git a/scripts/check-html b/scripts/check-html
--- a/scripts/check-html
+++ b/scripts/check-html
@@ -1,4 +1,6 @@
-#!/usr/bin/env bash -e
+#!/usr/bin/env bash
+
+set -e # halt script on error
 
 bundle exec jekyll build
 
